"""

Revision ID: b1e4c64104af
Revises: fc22564fb72d
Create Date: 2026-02-12 22:06:35.561728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e4c64104af'
down_revision: Union[str, Sequence[str], None] = 'fc22564fb72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_connect_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_connect_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_connect_token'), 'users', ['telegram_connect_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_connect_token'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'telegram_connect_token_expires_at')
    op.drop_column('users', 'telegram_connect_token')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
