"""

Revision ID: fc22564fb72d
Revises: 9bab9745873c
Create Date: 2026-02-09 19:35:39.576812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc22564fb72d'
down_revision: Union[str, Sequence[str], None] = '9bab9745873c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_detection_history',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_detection_history_user_id'), 'ai_detection_history', ['user_id'], unique=False)
    op.create_table('user_limits',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('daily_used', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monthly_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_used', sa.Integer(), nullable=False),
    sa.Column('monthly_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_limits_user_id'), 'user_limits', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_limits_user_id'), table_name='user_limits')
    op.drop_table('user_limits')
    op.drop_index(op.f('ix_ai_detection_history_user_id'), table_name='ai_detection_history')
    op.drop_table('ai_detection_history')
    # ### end Alembic commands ###
